export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';

export const ADMIN_GET_ORDERS_REQUEST = 'ADMIN_GET_ORDERS_REQUEST';
export const ADMIN_GET_ORDERS_SUCCESS = 'ADMIN_GET_ORDERS_SUCCESS';
export const ADMIN_GET_ORDERS_FAIL = 'ADMIN_GET_ORDERS_FAIL';

export const ADMIN_ORDER_LIST_REQUEST = 'ADMIN_ORDER_LIST_REQUEST';
export const ADMIN_ORDER_LIST_SUCCESS = 'ADMIN_ORDER_LIST_SUCCESS';
export const ADMIN_ORDER_LIST_FAIL = 'ADMIN_ORDER_LIST_FAIL';

export const ADMIN_ORDER_UPDATE_REQUEST = 'ADMIN_ORDER_UPDATE_REQUEST';
export const ADMIN_ORDER_UPDATE_SUCCESS = 'ADMIN_ORDER_UPDATE_SUCCESS';
export const ADMIN_ORDER_UPDATE_FAIL = 'ADMIN_ORDER_UPDATE_FAIL';
export const ADMIN_ORDER_UPDATE_RESET = 'ADMIN_ORDER_UPDATE_RESET'

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'; 
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';